version: "3.2"
services:

  api-gateway:
    image: bgornicki/engrave-api-gateway
    secrets:
      - JWT_SECRET
    environment:
      - WAIT_HOSTS=mongo:27017,redis:6379
      - BLOGS_DOMAINS=["dblog.pl"]
    
  blockchain-tracker:
    image: bgornicki/engrave-blockchain-tracker
    depends_on:
      - redis
    environment:
      - STARTING_BLOCK=29369963
      - WAIT_HOSTS=redis:6379

  blogs-renderer:
    image: bgornicki/engrave-blogs-renderer
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - redis
    environment:
      - WAIT_HOSTS=mongo:27017,redis:6379
      - DOMAIN=dblog.pl
      - AUTH_SERVICE=https://auth.dblog.pl
    volumes:
      - certbot:/app/certbot
      - /var/engrave/themes:/app/src/themes

  engrave-front-dashboard:
    image: bgornicki/engrave-front-dashboard
    environment:
      - DOMAIN=dblog.pl
      - SSL_EMAIL=engrave@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - BLOGS_DOMAINS=["dblog.pl"]
      - BLOGS_CATEGORIES=["Inne", "Finanse i ekonomia", "Lifestyle", "Jedzenie", "Sport", "Podróże", "Zdrowie i uroda", "Hobby", "Muzyka", "Dziennikarstwo", "Fotografia", "Technologia"]
      - WAIT_HOSTS=mongo:27017,redis:6379
      - SERVER_IP=172.104.225.127
      - PAYMENT_REDIRECT_URI=https://dblog.pl/dashboard/configure/
      - NAMECOM_API=api.name.com
      - DOMAIN_PRICE_SBD=15
      - DOMAIN_PRICE_STEEM=35
      - FRONT=dblog
      - STEEMCONNECT_ID=dblog.app
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
      - /var/engrave/themes:/app/themes
    depends_on:
      - mongo
    secrets:
      - NAMECOM_TOKEN
      - NAMECOM_USERNAME

  beta-dashboard:
    image: bgornicki/engrave-api-gateway
    secrets:
      - JWT_SECRET
    environment:
      - WAIT_HOSTS=mongo:27017

  image-uploader:
    image: bgornicki/engrave-image-uploader
    secrets:
      - IMGUR_KEY
      - IMGUR_CLIENT_ID

  nginx-configurator:
    image: bgornicki/engrave-nginx-configurator
    environment:
      - WAIT_HOSTS=mongo:27017
    volumes:
      - nginx_conf:/etc/nginx/conf.d

  ssl:
    image: bgornicki/engrave-ssl
    depends_on:
      - mongo
    volumes:
      - certbot:/app/certbot
      - nginx_certs:/etc/letsencrypt
    environment:
      - SSL_EMAIL=engrave@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - WAIT_HOSTS=mongo:27017
      - SERVER_IP=172.104.225.127
    
  statistics:
    image: bgornicki/engrave-statistics
    depends_on:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017,redis:6379

  auth:
    image: bgornicki/engrave-auth
    environment:
      - WAIT_HOSTS=mongo:27017,redis:6379
      - SC2_REDIRECT_DASHBOARD=https://auth.dblog.pl/dashboard/authorize
      - SC2_REDIRECT_BLOG=https://auth.dblog.pl/blog/authorize
      - STEEMCONNECT_ID=dblog.app
      - DASHBOARD_ADDR=https://beta.dblog.pl
    secrets:
      - SC2_APP_SECRET
      - JWT_SECRET
  
  mailer:
    image: bgornicki/engrave-mailer
    environment:
      - MAILGUN_SENDER_NAME=Platforma dBlog
      - MAILGUN_SENDER_ADDRESS=noreply@dblog.pl
    secrets:
      - MAILGUN_DOMAIN
      - MAILGUN_API_KEY
  
  sitemap-builder:
    image: bgornicki/engrave-sitemap-builder
    environment:
      - WAIT_HOSTS=redis:6379

  webpush-sender:
    image: bgornicki/engrave-webpush-sender

  vault-connector:
    image: bgornicki/engrave-vault-connector
    secrets:
      - VAULT_TOKEN

  nginx:
    image: bgornicki/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
    depends_on:
      - engrave

  mongo:
    image: mongo
    volumes:
      - mongo_db:/data/db

  redis:
    image: redis
    volumes:
      - redis_db:/data
  
  vault:
    image: vault
    volumes:
      - vault_db:/vault/file:rw
      - ./vault/config:/vault/config:rw
    entrypoint: vault server -config=/vault/config/production.json

volumes:
  nginx_certs:
  nginx_conf:
  certbot:
  redis_db:
  mongo_db:
  vault_db:

secrets:
  NAMECOM_TOKEN:
    external: true
  NAMECOM_USERNAME:
    external: true
  IMGUR_KEY:
    external: true
  IMGUR_CLIENT_ID:
    external: true
  SC2_APP_SECRET:
    external: true
  JWT_SECRET:
    external: true
  VAULT_TOKEN:
    external: true
  MAILGUN_DOMAIN:
    external: true
  MAILGUN_API_KEY:
    external: true