version: "3.2"
services:

  api-gateway:
    image: bgornicki/engrave-api-gateway
    secrets:
      - JWT_SECRET
    environment:
      - WAIT_HOSTS=mongo:27017
      - BLOGS_DOMAINS=["engrave.website", "engrave.site", "dblog.org"]

  blockchain-tracker:
    image: bgornicki/engrave-blockchain-tracker
    depends_on:
      - redis
    environment:
      - STARTING_BLOCK=29369963
      - WAIT_HOSTS=redis:6379

  blogs-renderer:
    image: bgornicki/engrave-blogs-renderer
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - redis
    environment:
      - WAIT_HOSTS=mongo:27017,redis:6379
      - DOMAIN=engrave.website
      - AUTH_SERVICE=https://auth.engrave.website
    volumes:
      - certbot:/app/certbot
      - themes:/app/src/themes
    secrets:
      - VAULT_TOKEN

  engrave-front-dashboard:
    image: bgornicki/engrave-front-dashboard
    environment:
      - DOMAIN=engrave.website
      - SSL_EMAIL=engrave@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - BLOGS_DOMAINS=["dblog.org", "engrave.website", "engrave.site"]
      - BLOGS_CATEGORIES=["Other", "Financial and economy", "Lifestyle", "Food", "Sport", "Travel", "Health and beauty", "Hobby", "Music", "Journalism", "Photography", "Technology"]
      - WAIT_HOSTS=mongo:27017,redis:6379
      - SERVER_IP=139.162.185.235
      - PAYMENT_REDIRECT_URI=https://engrave.website/dashboard/configure/
      - NAMECOM_API=api.name.com
      - DOMAIN_PRICE_SBD=15
      - DOMAIN_PRICE_STEEM=35
      - FRONT=engrave
      - STEEMCONNECT_ID=engrave.app
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
      - themes:/app/themes
    depends_on:
      - mongo
    secrets:
      - NAMECOM_TOKEN
      - NAMECOM_USERNAME

  beta-dashboard:
    image: bgornicki/engrave-api-gateway
    secrets:
      - JWT_SECRET
    environment:
      - WAIT_HOSTS=mongo:27017

  image-uploader:
    image: bgornicki/engrave-image-uploader
    secrets:
      - IMGUR_KEY
      - IMGUR_CLIENT_ID

  nginx-configurator:
    image: bgornicki/engrave-nginx-configurator
    environment:
      - WAIT_HOSTS=mongo:27017
    volumes:
      - nginx_conf:/etc/nginx/conf.d
  
  ssl:
    image: bgornicki/engrave-ssl
    depends_on:
      - mongo
    volumes:
      - certbot:/app/certbot
      - nginx_certs:/etc/letsencrypt
    environment:
      - SSL_EMAIL=engrave@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - WAIT_HOSTS=mongo:27017
      - SERVER_IP=139.162.185.235
  
  statistics:
    image: bgornicki/engrave-statistics
    depends_on:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017  

  auth:
    image: bgornicki/engrave-auth
    environment:
      - WAIT_HOSTS=mongo:27017,redis:6379
      - SC2_REDIRECT_DASHBOARD=https://auth.engrave.website/dashboard/authorize
      - SC2_REDIRECT_BLOG=https://auth.engrave.website/blog/authorize
      - STEEMCONNECT_ID=engrave.app
      - DASHBOARD_ADDR=https://beta.engrave.website
    secrets:
      - SC2_APP_SECRET
      - JWT_SECRET
      - VAULT_TOKEN

  nginx:
    image: bgornicki/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
    depends_on:
      - engrave

  mongo:
    image: mongo
    volumes:
      - db-data:/data/db

  redis:
    image: redis
    volumes:
      - redis-data:/data
  
  vault:
    image: vault
    volumes:
      - vault_db:/vault/file:rw
      - ./vault/config:/vault/config:rw
    entrypoint: vault server -config=/vault/config/vault.json

volumes:
  db-data:
  nginx_certs:
  nginx_conf:
  certbot:
  themes:
  redis-data:
  vault_db:

secrets:
  NAMECOM_TOKEN:
    external: true
  NAMECOM_USERNAME:
    external: true
  IMGUR_KEY:
    external: true
  IMGUR_CLIENT_ID:
    external: true
  SC2_APP_SECRET:
    external: true
  JWT_SECRET:
    external: true
  VAULT_TOKEN:
    external: true